# Generated by Django 4.0.3 on 2022-04-11 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
