# Generated by Django 4.0.3 on 2022-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
