# Generated by Django 4.0.3 on 2022-04-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_booking_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booke',
        ),
    ]
